version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  generate_dummy_data:
    run: r:latest analysis/generate_dummy_data.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        dummy_data_admissions: output/dummy_data/dummy_data_admissions.csv.gz
        dummy_data_outpatient: output/dummy_data/dummy_data_outpatient.csv.gz
        dummy_data_gp: output/dummy_data/dummy_data_gp.csv.gz
        dummy_data_testing_negative: output/dummy_data/dummy_data_testing_negative.csv.gz
        dummy_data_testing_positive: output/dummy_data/dummy_data_testing_positive.csv.gz

  generate_admissions:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_admissions
        --index-date-range "2019-12-30 to 2020-12-28 by week"
        --output-format csv.gz
        --skip-existing 
        --output-dir=output/data_weekly
    dummy_data_file: output/dummy_data/dummy_data_admissions.csv.gz
    needs: [generate_dummy_data]
    outputs:
      highly_sensitive:
        data_admissions: output/data_weekly/input_admissions_20*.csv.gz

  generate_outpatient:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_outpatient
        --index-date-range "2019-03-11 to 2022-01-31 by week"
        --output-format csv.gz
        --skip-existing 
        --output-dir=output/data_weekly
    dummy_data_file: output/dummy_data/dummy_data_outpatient.csv.gz
    needs: [generate_dummy_data]
    outputs:
      highly_sensitive:
        data_outpatient: output/data_weekly/input_outpatient_20*.csv.gz

  generate_gp:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_gp
        --index-date-range "2018-12-31 to 2022-01-31 by week"
        --output-format csv.gz
        --skip-existing 
        --output-dir=output/data_weekly
    dummy_data_file: output/dummy_data/dummy_data_gp.csv.gz
    needs: [generate_dummy_data]
    outputs:
      highly_sensitive:
        data_gp_contacts: output/data_weekly/input_gp_20*.csv.gz

  generate_covid_tests_negative:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_covid_tests_negative
        --index-date-range "2019-12-30 to 2022-01-31 by week"
        --output-format csv.gz
        --skip-existing 
        --output-dir=output/data_weekly
    dummy_data_file: output/dummy_data/dummy_data_testing_negative.csv.gz
    needs: [generate_dummy_data]
    outputs:
      highly_sensitive:
        data_negative_tests: output/data_weekly/input_covid_tests_negative_20*.csv.gz

  generate_covid_tests_positive:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_covid_tests_positive
        --index-date-range "2019-12-30 to 2022-01-31 by week"
        --output-format csv.gz
        --skip-existing 
        --output-dir=output/data_weekly
    dummy_data_file: output/dummy_data/dummy_data_testing_positive.csv.gz
    needs: [generate_dummy_data]
    outputs:
      highly_sensitive:
        data_positive_tests: output/data_weekly/input_covid_tests_positive_20*.csv.gz

  process_data:
    run: r:latest analysis/04_summarise_admissions.R
    needs: [generate_study_population, generate_admissions, generate_outpatient,
            generate_gp, generate_covid_tests_negative, generate_covid_tests_positive]
    outputs:
      highly_sensitive:
        datasets: output/datasets/*.rds
      moderately_sensitive:
        plots: output/extract_descriptives/figures/*.jpeg
        tables: output/extract_descriptives/tables/*.csv