version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  generate_high_admissions:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_high_admissions --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_high_admissions.csv.gz

  generate_high_outpatient:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_high_outpatient --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_high_outpatient.csv.gz

  generate_high_gp:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_high_gp --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_high_gp.csv.gz

  process_data:
    run: r:latest analysis/01_process_data.R
    needs: [generate_study_population, generate_high_admissions, generate_high_outpatient, generate_high_gp]
    outputs:
      highly_sensitive:
        data1: output/data/*.rds
      moderately_sensitive:
        filter_log: output/data/*.csv

  descriptives:
    run: r:latest analysis/02_descriptives.R
    needs: [process_data]
    outputs:
      moderately_sensitive:
        plots: output/descriptive/plots/*.jpeg
        tables: output/descriptive/tables/*.csv