version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  process_data:
    run: r:latest analysis/process_data.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        data1: output/data/data_processed.rds

  descriptives:
    run: r:latest analysis/descriptives.R
    needs: [process_data]
    outputs:
      moderately_sensitive:
        plots: output/descriptive/plots/*.jpeg
        tables: output/descriptive/tables/*.csv