version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  generate_dummy_data:
    run: r:latest analysis/01_generate_dummy_data.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        dummy_data_admissions: output/dummy_data/dummy_data_admissions.csv.gz
        dummy_data_outpatient: output/dummy_data/dummy_data_outpatient.csv.gz
        dummy_data_gp: output/dummy_data/dummy_data_gp.csv.gz
        dummy_data_testing_negative: output/dummy_data/dummy_data_testing_negative.csv.gz
        dummy_data_testing_positive: output/dummy_data/dummy_data_testing_positive.csv.gz

  generate_admissions:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_admissions
        --index-date-range "2018-10-01 to 2022-05-02 by week"
        --output-format csv.gz
        --output-dir=output/data_weekly
    dummy_data_file: output/dummy_data/dummy_data_admissions.csv.gz
    needs: [generate_dummy_data]
    outputs:
      highly_sensitive:
        data_admissions: output/data_weekly/input_admissions_20*.csv.gz

  generate_outpatient:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_outpatient
        --index-date-range "2019-03-11 to 2022-05-02 by week"
        --output-format csv.gz
        --output-dir=output/data_weekly
    dummy_data_file: output/dummy_data/dummy_data_outpatient.csv.gz
    needs: [generate_dummy_data]
    outputs:
      highly_sensitive:
        data_outpatient: output/data_weekly/input_outpatient_20*.csv.gz

  generate_gp:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_gp
        --index-date-range "2018-12-31 to 2022-05-02 by week"
        --output-format csv.gz
        --output-dir=output/data_weekly
    dummy_data_file: output/dummy_data/dummy_data_gp.csv.gz
    needs: [generate_dummy_data]
    outputs:
      highly_sensitive:
        data_gp_contacts: output/data_weekly/input_gp_20*.csv.gz

  generate_covid_tests_negative:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_covid_tests_negative
        --index-date-range "2019-12-30 to 2022-05-02 by week"
        --output-format csv.gz
        --output-dir=output/data_weekly
    dummy_data_file: output/dummy_data/dummy_data_testing_negative.csv.gz
    needs: [generate_dummy_data]
    outputs:
      highly_sensitive:
        data_negative_tests: output/data_weekly/input_covid_tests_negative_20*.csv.gz

  generate_covid_tests_positive:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_covid_tests_positive
        --index-date-range "2019-12-30 to 2022-05-02 by week"
        --output-format csv.gz
        --output-dir=output/data_weekly
    dummy_data_file: output/dummy_data/dummy_data_testing_positive.csv.gz
    needs: [generate_dummy_data]
    outputs:
      highly_sensitive:
        data_positive_tests: output/data_weekly/input_covid_tests_positive_20*.csv.gz

  process_patient_ids:
    run: r:latest analysis/02_process_patient_ids.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        data_id: output/data/data_id.rds

  process_admissions_data:
    run: r:latest analysis/02_process_admissions_data.R
    needs: [generate_admissions, process_patient_ids]
    outputs:
      highly_sensitive:
        data_admissions: output/data/data_admissions.rds
      moderately_sensitive:
        diagnostics_admissions: output/diagnostics/diagnostics_admissions.csv
        diagnostics_admissions2: output/diagnostics/overlap_admissions.csv
        plots_admissions: output/descriptives/data_admissions/*.jpeg

  process_outpatient_data:
    run: r:latest analysis/02_process_outpatient_data.R
    needs: [generate_outpatient, process_patient_ids]
    outputs:
      highly_sensitive:
        data_outpatient: output/data/data_outpatient.rds
      moderately_sensitive:
        diagnostics_outpatient: output/diagnostics/diagnostics_outpatient.csv
        plots_outpatient: output/descriptives/data_outpatient/*.jpeg

  process_gp_data:
    run: r:latest analysis/02_process_gp_data.R
    needs: [generate_gp, process_patient_ids]
    outputs:
      highly_sensitive:
        data_gp: output/data/data_gp.rds
      moderately_sensitive:
        diagnostics_gp: output/diagnostics/diagnostics_gp.csv
        plots_gp: output/descriptives/data_gp/*.jpeg

  process_testing_data:
    run: r:latest analysis/02_process_testing_data.R
    needs: [generate_covid_tests_negative, generate_covid_tests_positive, process_patient_ids]
    outputs:
      highly_sensitive:
        data_testing: output/data/data_testing.rds
      moderately_sensitive:
        diagnostics_testing: output/diagnostics/diagnostics_testing.csv
        plots_testing: output/descriptives/data_testing/*.jpeg

  process_patient_data:
    run: r:latest analysis/02_process_patient_data.R
    needs: [generate_study_population, process_admissions_data, process_testing_data]
    outputs:
      highly_sensitive:
        data_patient: output/data/data_patient.rds

  summary_datasets:
    run: r:latest -e 'rmarkdown::render("analysis/04_summary_datasets.Rmd", output_dir = "output/descriptives")'
    needs: [generate_covid_tests_negative, generate_covid_tests_positive, process_patient_ids]
    outputs:
      moderately_sensitive:
        summary_datasets_html: output/descriptives/04_summary_datasets.html