version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_contact_counts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_contact_counts --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_contact_counts.csv.gz

  descriptives_count_data:
    run: r:latest analysis/00_count_data.R
    needs: [generate_contact_counts]
    outputs:
      moderately_sensitive:
        plots: output/descriptive/counts/*.jpeg
        tables: output/descriptive/counts/*.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  generate_high_admissions:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_high_admissions --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_high_admissions.csv.gz

  generate_high_outpatient:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_high_outpatient --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_high_outpatient.csv.gz

  generate_high_gp:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_high_gp --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_high_gp.csv.gz

  process_data:
    run: r:latest analysis/01_process_data.R
    needs: [generate_study_population, generate_high_admissions, generate_high_outpatient, generate_high_gp]
    outputs:
      highly_sensitive:
        data1: output/data/*.rds
      moderately_sensitive:
        diagnostics: output/diagnostics/*.csv

  descriptives:
    run: r:latest analysis/02_descriptives.R
    needs: [process_data]
    outputs:
      moderately_sensitive:
        plots: output/descriptive/plots/*.jpeg
        tables: output/descriptive/tables/*.csv

  create_cohorts:
    run: r:latest analysis/03_create_cohorts.R
    needs: [process_data]
    outputs:
      highly_sensitive:
        data1: output/data/cohorts/*.rds

  obj_1_analysis:
    run: r:latest analysis/04_analysis_obj_1.R
    needs: [process_data, create_cohorts]
    outputs:
      moderately_sensitive:
        plots: output/descriptive/obj_1/*.jpeg