version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_contact_counts:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_contact_counts
        --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_contact_counts.csv.gz

  descriptives_count_data:
    run: r:latest analysis/00_count_data.R
    needs: [generate_contact_counts]
    outputs:
      moderately_sensitive:
        plots: output/descriptive/counts/*.jpeg
        tables: output/descriptive/counts/*.csv

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  generate_admissions:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_admissions
        --index-date-range "2018-10-01 to 2018-11-01 by month"
        --output-format csv.gz
    outputs:
      highly_sensitive:
        data_admissions: output/input_admissions_20*.csv.gz

  generate_outpatient:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_outpatient
        --index-date-range "2019-01-01 to 2019-04-01 by month"
        --output-format csv.gz
    outputs:
      highly_sensitive:
        data_outpatient: output/input_outpatient_20*.csv.gz

  generate_gp:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_gp
        --index-date-range "2019-01-01 to 2019-04-01 by month"
        --output-format csv.gz
    outputs:
      highly_sensitive:
        data_gp_contacts: output/input_gp_20*.csv.gz

  generate_covid_tests_negative:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_covid_tests_negative
        --index-date-range "2020-01-01 to 2020-04-01 by month"
        --output-format csv.gz
    outputs:
      highly_sensitive:
        data_negative_tests: output/input_covid_tests_negative_20*.csv.gz

  generate_covid_tests_positive:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_covid_tests_positive
        --index-date-range "2020-01-01 to 2020-04-01 by month"
        --output-format csv.gz
    outputs:
      highly_sensitive:
        data_positive_tests: output/input_covid_tests_positive_20*.csv.gz

  process_data:
    run: r:latest analysis/04_summarise_admissions.R
    needs: [generate_study_population, generate_admissions, generate_outpatient,
            generate_gp, generate_covid_tests_negative, generate_covid_tests_positive]
    outputs:
      highly_sensitive:
        datasets: output/datasets/*.rds
      moderately_sensitive:
        plots: output/extract_descriptives/figures/*.jpeg
        tables: output/extract_descriptives/tables/*.csv